version: "2"

services:
 gitserver: 
    image: haenerconsulting/gitserver
    environment:
      - SERVER_NAME="git.haenerconsulting.com"
      - LDAP_SERVER="openldap.openldap"
      - LDAP_BASE_DN="dc=haenerconsulting.com,dc=com"
      - LDAP_FILTER="(uid=$)"
      - LDAP_REQUIRE="group=cn=git-developers,ou=groups,dc=haenerconsulting,dc=com|user=admin"
    ports:
      - "8083:80"
    volumes:
      - git-repositories:/git
      - git-var:/var
    restart: unless-stopped

volumes:
  git-repositories:
    external: false
    driver: rancher-nfs
    driver_opts:
      host: atlas
      export: /volume1/home/git/repositories
  git-var:
    external: false
    driver: rancher-nfs
    driver_opts:
      host: atlas
      export: /volume1/home/git/data
